version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend/nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/nextjs:/app
      - /app/node_modules
      - /app/.next

  streamlit:
    build:
      context: ./frontend/streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend/streamlit_app:/app
