services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8020:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
      - ./data_connectors:/app/data_connectors
    environment:
      - PYTHONPATH=/app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/nextjs
      dockerfile: Dockerfile
    ports:
      - "3020:3000"
    volumes:
      - ./frontend/nextjs:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

  streamlit:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONPATH=/app
    command: streamlit run run_dashboard.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped
