"""sync_all_models_with_sqlite

Revision ID: db8bb6b6488f
Revises: 004
Create Date: 2025-07-20 23:50:07.327558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8bb6b6488f'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_domain_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_domain_id'], ['ai_domains.id'], name=op.f('fk_ai_domains_parent_domain_id_ai_domains')),
    sa.ForeignKeyConstraint(['parent_id'], ['ai_domains.id'], name=op.f('fk_ai_domains_parent_id_ai_domains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_domains'))
    )
    op.create_index(op.f('ix_ai_domains_id'), 'ai_domains', ['id'], unique=False)
    op.create_index(op.f('ix_ai_domains_name'), 'ai_domains', ['name'], unique=True)
    op.create_table('collaboration_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaboration_potential', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collaboration_suggestions'))
    )
    op.create_index(op.f('ix_collaboration_suggestions_id'), 'collaboration_suggestions', ['id'], unique=False)
    op.create_table('community_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('reputation_score', sa.Integer(), nullable=True),
    sa.Column('contributions_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_users'))
    )
    op.create_index(op.f('ix_community_users_email'), 'community_users', ['email'], unique=True)
    op.create_index(op.f('ix_community_users_id'), 'community_users', ['id'], unique=False)
    op.create_index(op.f('ix_community_users_username'), 'community_users', ['username'], unique=True)
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('total_opportunities_found', sa.Integer(), nullable=True),
    sa.Column('successful_checks', sa.Integer(), nullable=True),
    sa.Column('failed_checks', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('parser_config', sa.Text(), nullable=True),
    sa.Column('classification_keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources'))
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_data_sources_name'), 'data_sources', ['name'], unique=False)
    op.create_table('funding_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['funding_categories.id'], name=op.f('fk_funding_categories_parent_id_funding_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_categories'))
    )
    op.create_index(op.f('ix_funding_categories_id'), 'funding_categories', ['id'], unique=False)
    op.create_index(op.f('ix_funding_categories_name'), 'funding_categories', ['name'], unique=True)
    op.create_table('funding_stage_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('opportunity_count', sa.Integer(), nullable=True),
    sa.Column('avg_funding', sa.Float(), nullable=True),
    sa.Column('total_funding', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('avg_months_in_stage', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_stage_metrics'))
    )
    op.create_index(op.f('ix_funding_stage_metrics_id'), 'funding_stage_metrics', ['id'], unique=False)
    op.create_table('funding_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('typical_amount_range', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('requires_equity', sa.Boolean(), nullable=True),
    sa.Column('requires_repayment', sa.Boolean(), nullable=True),
    sa.Column('average_processing_time_days', sa.Integer(), nullable=True),
    sa.Column('success_rate_percentage', sa.Integer(), nullable=True),
    sa.Column('required_stage', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_types'))
    )
    op.create_index(op.f('ix_funding_types_category'), 'funding_types', ['category'], unique=False)
    op.create_index(op.f('ix_funding_types_id'), 'funding_types', ['id'], unique=False)
    op.create_index(op.f('ix_funding_types_name'), 'funding_types', ['name'], unique=True)
    op.create_table('geographic_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('parent_scope_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_scope_id'], ['geographic_scopes.id'], name=op.f('fk_geographic_scopes_parent_scope_id_geographic_scopes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geographic_scopes'))
    )
    op.create_index(op.f('ix_geographic_scopes_code'), 'geographic_scopes', ['code'], unique=False)
    op.create_index(op.f('ix_geographic_scopes_id'), 'geographic_scopes', ['id'], unique=False)
    op.create_index(op.f('ix_geographic_scopes_name'), 'geographic_scopes', ['name'], unique=True)
    op.create_index(op.f('ix_geographic_scopes_type'), 'geographic_scopes', ['type'], unique=False)
    op.create_table('module_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('avg_processing_time', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('circuit_breaker_open', sa.Boolean(), nullable=True),
    sa.Column('circuit_breaker_failures', sa.Integer(), nullable=True),
    sa.Column('circuit_breaker_threshold', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_health'))
    )
    op.create_index(op.f('ix_module_health_id'), 'module_health', ['id'], unique=False)
    op.create_index(op.f('ix_module_health_module_type'), 'module_health', ['module_type'], unique=True)
    op.create_index(op.f('ix_module_health_status'), 'module_health', ['status'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('provider_type', sa.String(length=20), nullable=True),
    sa.Column('recipient_type', sa.String(length=20), nullable=True),
    sa.Column('startup_stage', sa.String(length=30), nullable=True),
    sa.Column('funding_model', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('funding_capacity', sa.String(length=50), nullable=True),
    sa.Column('focus_areas', sa.Text(), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('ai_relevance_score', sa.Integer(), nullable=True),
    sa.Column('africa_relevance_score', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('update_frequency', sa.String(length=20), nullable=True),
    sa.Column('funding_announcement_url', sa.Text(), nullable=True),
    sa.Column('monitoring_status', sa.String(length=20), nullable=True),
    sa.Column('monitoring_reliability', sa.Integer(), nullable=True),
    sa.Column('opportunities_discovered', sa.Integer(), nullable=True),
    sa.Column('unique_opportunities_added', sa.Integer(), nullable=True),
    sa.Column('duplicate_rate', sa.Integer(), nullable=True),
    sa.Column('data_completeness_score', sa.Integer(), nullable=True),
    sa.Column('community_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('enrichment_status', sa.String(length=20), nullable=True),
    sa.Column('enrichment_completeness', sa.Integer(), nullable=True),
    sa.Column('last_enrichment_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrichment_sources', sa.Text(), nullable=True),
    sa.Column('founding_story', sa.Text(), nullable=True),
    sa.Column('cultural_significance', sa.Text(), nullable=True),
    sa.Column('local_partnerships', sa.Text(), nullable=True),
    sa.Column('community_impact', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('mission_statement', sa.Text(), nullable=True),
    sa.Column('vision_statement', sa.Text(), nullable=True),
    sa.Column('leadership_team', sa.Text(), nullable=True),
    sa.Column('notable_achievements', sa.Text(), nullable=True),
    sa.Column('awards_recognition', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('annual_budget_range', sa.String(length=50), nullable=True),
    sa.Column('staff_size_range', sa.String(length=50), nullable=True),
    sa.Column('languages_supported', sa.Text(), nullable=True),
    sa.Column('total_funding_distributed', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('beneficiaries_count', sa.Integer(), nullable=True),
    sa.Column('success_stories', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_africa_relevance_score'), 'organizations', ['africa_relevance_score'], unique=False)
    op.create_index(op.f('ix_organizations_ai_relevance_score'), 'organizations', ['ai_relevance_score'], unique=False)
    op.create_index(op.f('ix_organizations_enrichment_status'), 'organizations', ['enrichment_status'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_monitoring_status'), 'organizations', ['monitoring_status'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_provider_type'), 'organizations', ['provider_type'], unique=False)
    op.create_index(op.f('ix_organizations_recipient_type'), 'organizations', ['recipient_type'], unique=False)
    op.create_index(op.f('ix_organizations_role'), 'organizations', ['role'], unique=False)
    op.create_index(op.f('ix_organizations_source_type'), 'organizations', ['source_type'], unique=False)
    op.create_index(op.f('ix_organizations_type'), 'organizations', ['type'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=True),
    sa.Column('module_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('source_data', sa.JSON(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('items_succeeded', sa.Integer(), nullable=True),
    sa.Column('items_failed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    op.create_index(op.f('ix_processing_jobs_id'), 'processing_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_job_type'), 'processing_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_processing_jobs_module_type'), 'processing_jobs', ['module_type'], unique=False)
    op.create_index(op.f('ix_processing_jobs_priority'), 'processing_jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_table('source_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('duplicate_rate', sa.Float(), nullable=True),
    sa.Column('processing_success_rate', sa.Float(), nullable=True),
    sa.Column('content_relevance_score', sa.Float(), nullable=True),
    sa.Column('total_items_processed', sa.Integer(), nullable=True),
    sa.Column('successful_items', sa.Integer(), nullable=True),
    sa.Column('duplicate_items', sa.Integer(), nullable=True),
    sa.Column('invalid_items', sa.Integer(), nullable=True),
    sa.Column('last_processed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('quality_grade', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_quality'))
    )
    op.create_index(op.f('ix_source_quality_id'), 'source_quality', ['id'], unique=False)
    op.create_index(op.f('ix_source_quality_quality_grade'), 'source_quality', ['quality_grade'], unique=False)
    op.create_index(op.f('ix_source_quality_source_name'), 'source_quality', ['source_name'], unique=True)
    op.create_index(op.f('ix_source_quality_source_type'), 'source_quality', ['source_type'], unique=False)
    op.create_table('stage_progression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.String(length=50), nullable=False),
    sa.Column('to_stage', sa.String(length=50), nullable=False),
    sa.Column('progression_rate', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_progression'))
    )
    op.create_index(op.f('ix_stage_progression_id'), 'stage_progression', ['id'], unique=False)
    op.create_table('underrepresented_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_underrepresented_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_underrepresented_groups_name'))
    )
    op.create_index(op.f('ix_underrepresented_groups_id'), 'underrepresented_groups', ['id'], unique=False)
    op.create_table('africa_intelligence_feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('organization_name', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('provider_organization_id', sa.Integer(), nullable=True),
    sa.Column('recipient_organization_id', sa.Integer(), nullable=True),
    sa.Column('funding_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('funding_amount', sa.Text(), nullable=True),
    sa.Column('total_funding_pool', sa.Float(), nullable=True),
    sa.Column('funding_type', sa.String(length=20), nullable=True),
    sa.Column('min_amount_per_project', sa.Float(), nullable=True),
    sa.Column('max_amount_per_project', sa.Float(), nullable=True),
    sa.Column('exact_amount_per_project', sa.Float(), nullable=True),
    sa.Column('estimated_project_count', sa.Integer(), nullable=True),
    sa.Column('project_count_range', sa.JSON(), nullable=True),
    sa.Column('amount_min', sa.Float(), nullable=True),
    sa.Column('amount_max', sa.Float(), nullable=True),
    sa.Column('amount_exact', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('deadline_urgency', sa.String(length=10), nullable=True),
    sa.Column('application_deadline_type', sa.String(length=20), nullable=True),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('funding_start_date', sa.Date(), nullable=True),
    sa.Column('project_duration', sa.String(length=100), nullable=True),
    sa.Column('application_process', sa.Text(), nullable=True),
    sa.Column('selection_criteria', sa.JSON(), nullable=True),
    sa.Column('target_audience', sa.JSON(), nullable=True),
    sa.Column('ai_subsectors', sa.JSON(), nullable=True),
    sa.Column('development_stage', sa.JSON(), nullable=True),
    sa.Column('collaboration_required', sa.Boolean(), nullable=True),
    sa.Column('gender_focused', sa.Boolean(), nullable=True),
    sa.Column('youth_focused', sa.Boolean(), nullable=True),
    sa.Column('reporting_requirements', sa.JSON(), nullable=True),
    sa.Column('grant_reporting_requirements', sa.Text(), nullable=True),
    sa.Column('grant_duration_months', sa.Integer(), nullable=True),
    sa.Column('grant_renewable', sa.Boolean(), nullable=True),
    sa.Column('no_strings_attached', sa.Boolean(), nullable=True),
    sa.Column('project_based', sa.Boolean(), nullable=True),
    sa.Column('interim_reporting_required', sa.Boolean(), nullable=True),
    sa.Column('final_report_required', sa.Boolean(), nullable=True),
    sa.Column('financial_reporting_frequency', sa.String(length=20), nullable=True),
    sa.Column('intellectual_property_rights', sa.Text(), nullable=True),
    sa.Column('publication_requirements', sa.Text(), nullable=True),
    sa.Column('equity_percentage', sa.Float(), nullable=True),
    sa.Column('valuation_cap', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('repayment_terms', sa.Text(), nullable=True),
    sa.Column('investor_rights', sa.Text(), nullable=True),
    sa.Column('post_investment_support', sa.Text(), nullable=True),
    sa.Column('expected_roi', sa.Float(), nullable=True),
    sa.Column('liquidation_preference', sa.Text(), nullable=True),
    sa.Column('board_representation', sa.Boolean(), nullable=True),
    sa.Column('anti_dilution_protection', sa.Text(), nullable=True),
    sa.Column('drag_along_rights', sa.Boolean(), nullable=True),
    sa.Column('tag_along_rights', sa.Boolean(), nullable=True),
    sa.Column('competition_phases', sa.JSON(), nullable=True),
    sa.Column('judging_criteria', sa.JSON(), nullable=True),
    sa.Column('submission_format', sa.Text(), nullable=True),
    sa.Column('presentation_required', sa.Boolean(), nullable=True),
    sa.Column('team_size_limit', sa.Integer(), nullable=True),
    sa.Column('intellectual_property_ownership', sa.Text(), nullable=True),
    sa.Column('community_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('application_tips', sa.Text(), nullable=True),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('application_count', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('ai_relevance_score', sa.Float(), nullable=True),
    sa.Column('africa_relevance_score', sa.Float(), nullable=True),
    sa.Column('funding_relevance_score', sa.Float(), nullable=True),
    sa.Column('overall_relevance_score', sa.Float(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('discovered_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parsed_with_ai', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('title_hash', sa.String(length=64), nullable=True),
    sa.Column('semantic_hash', sa.String(length=64), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('content_classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_method', sa.String(length=50), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('validation_confidence_score', sa.Float(), nullable=True),
    sa.Column('validation_flags', sa.JSON(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by', sa.String(length=50), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=True),
    sa.Column('ingestion_module', sa.String(length=50), nullable=True),
    sa.Column('processing_id', sa.String(length=50), nullable=True),
    sa.Column('processing_metadata', sa.JSON(), nullable=True),
    sa.Column('detected_language', sa.String(length=5), nullable=True),
    sa.Column('translation_status', sa.JSON(), nullable=True),
    sa.Column('is_multilingual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['funding_type_id'], ['funding_types.id'], name=op.f('fk_africa_intelligence_feed_funding_type_id_funding_types')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_africa_intelligence_feed_organization_id_organizations')),
    sa.ForeignKeyConstraint(['provider_organization_id'], ['organizations.id'], name=op.f('fk_africa_intelligence_feed_provider_organization_id_organizations')),
    sa.ForeignKeyConstraint(['recipient_organization_id'], ['organizations.id'], name=op.f('fk_africa_intelligence_feed_recipient_organization_id_organizations')),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['community_users.id'], name=op.f('fk_africa_intelligence_feed_submitted_by_user_id_community_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_africa_intelligence_feed')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_africa_intelligence_feed_content_hash'))
    )
    op.create_index(op.f('ix_africa_intelligence_feed_application_deadline_type'), 'africa_intelligence_feed', ['application_deadline_type'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_community_rating'), 'africa_intelligence_feed', ['community_rating'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_content_type'), 'africa_intelligence_feed', ['content_type'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_currency'), 'africa_intelligence_feed', ['currency'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_deadline_urgency'), 'africa_intelligence_feed', ['deadline_urgency'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_funding_type'), 'africa_intelligence_feed', ['funding_type'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_funding_type_id'), 'africa_intelligence_feed', ['funding_type_id'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_id'), 'africa_intelligence_feed', ['id'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_ingestion_module'), 'africa_intelligence_feed', ['ingestion_module'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_organization_id'), 'africa_intelligence_feed', ['organization_id'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_processing_id'), 'africa_intelligence_feed', ['processing_id'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_provider_organization_id'), 'africa_intelligence_feed', ['provider_organization_id'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_recipient_organization_id'), 'africa_intelligence_feed', ['recipient_organization_id'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_semantic_hash'), 'africa_intelligence_feed', ['semantic_hash'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_status'), 'africa_intelligence_feed', ['status'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_title_hash'), 'africa_intelligence_feed', ['title_hash'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_url_hash'), 'africa_intelligence_feed', ['url_hash'], unique=False)
    op.create_index(op.f('ix_africa_intelligence_feed_validation_status'), 'africa_intelligence_feed', ['validation_status'], unique=False)
    op.create_table('featured_founders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('funding_secured', sa.Float(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('ai_domain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ai_domain_id'], ['ai_domains.id'], name=op.f('fk_featured_founders_ai_domain_id_ai_domains')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_featured_founders_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_featured_founders'))
    )
    op.create_index(op.f('ix_featured_founders_id'), 'featured_founders', ['id'], unique=False)
    op.create_table('gender_funding_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('funding_amount', sa.Float(), nullable=True),
    sa.Column('opportunity_count', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_gender_funding_data_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gender_funding_data'))
    )
    op.create_index(op.f('ix_gender_funding_data_id'), 'gender_funding_data', ['id'], unique=False)
    op.create_table('inclusion_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funding_percentage', sa.Float(), nullable=True),
    sa.Column('opportunity_count', sa.Integer(), nullable=True),
    sa.Column('total_funding', sa.Float(), nullable=True),
    sa.Column('change_from_previous_year', sa.Float(), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['underrepresented_groups.id'], name=op.f('fk_inclusion_metrics_group_id_underrepresented_groups')),
    sa.ForeignKeyConstraint(['region_id'], ['geographic_scopes.id'], name=op.f('fk_inclusion_metrics_region_id_geographic_scopes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inclusion_metrics'))
    )
    op.create_index(op.f('ix_inclusion_metrics_id'), 'inclusion_metrics', ['id'], unique=False)
    op.create_table('organization_collaboration',
    sa.Column('collaboration_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaboration_suggestions.id'], name=op.f('fk_organization_collaboration_collaboration_id_collaboration_suggestions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_collaboration_organization_id_organizations'))
    )
    op.create_table('organization_geographic_focus',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('geographic_scope_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geographic_scope_id'], ['geographic_scopes.id'], name=op.f('fk_organization_geographic_focus_geographic_scope_id_geographic_scopes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_geographic_focus_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'geographic_scope_id', name=op.f('pk_organization_geographic_focus'))
    )
    op.create_table('rfps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_rfps_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rfps'))
    )
    op.create_index(op.f('ix_rfps_id'), 'rfps', ['id'], unique=False)
    op.create_index(op.f('ix_rfps_title'), 'rfps', ['title'], unique=False)
    op.create_table('content_fingerprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('title_hash', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('semantic_hash', sa.String(length=64), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=True),
    sa.Column('signature_hash', sa.String(length=64), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('funding_amount', sa.Float(), nullable=True),
    sa.Column('funding_currency', sa.String(length=10), nullable=True),
    sa.Column('announcement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('url_domain', sa.String(length=255), nullable=True),
    sa.Column('key_phrases', sa.JSON(), nullable=True),
    sa.Column('extraction_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['africa_intelligence_feed.id'], name=op.f('fk_content_fingerprints_opportunity_id_africa_intelligence_feed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_fingerprints'))
    )
    op.create_index(op.f('ix_content_fingerprints_content_hash'), 'content_fingerprints', ['content_hash'], unique=False)
    op.create_index(op.f('ix_content_fingerprints_funding_amount'), 'content_fingerprints', ['funding_amount'], unique=False)
    op.create_index(op.f('ix_content_fingerprints_id'), 'content_fingerprints', ['id'], unique=False)
    op.create_index(op.f('ix_content_fingerprints_opportunity_id'), 'content_fingerprints', ['opportunity_id'], unique=True)
    op.create_index(op.f('ix_content_fingerprints_organization_name'), 'content_fingerprints', ['organization_name'], unique=False)
    op.create_index(op.f('ix_content_fingerprints_semantic_hash'), 'content_fingerprints', ['semantic_hash'], unique=False)
    op.create_index(op.f('ix_content_fingerprints_signature_hash'), 'content_fingerprints', ['signature_hash'], unique=False)
    op.create_index(op.f('ix_content_fingerprints_title_hash'), 'content_fingerprints', ['title_hash'], unique=False)
    op.create_index(op.f('ix_content_fingerprints_url_domain'), 'content_fingerprints', ['url_domain'], unique=False)
    op.create_index(op.f('ix_content_fingerprints_url_hash'), 'content_fingerprints', ['url_hash'], unique=False)
    op.create_table('duplicate_detections',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('original_opportunity_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_opportunity_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_type', sa.String(length=30), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('action_taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_taken_by', sa.String(length=50), nullable=True),
    sa.Column('detection_method', sa.String(length=50), nullable=True),
    sa.Column('detection_details', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_opportunity_id'], ['africa_intelligence_feed.id'], name=op.f('fk_duplicate_detections_duplicate_opportunity_id_africa_intelligence_feed')),
    sa.ForeignKeyConstraint(['original_opportunity_id'], ['africa_intelligence_feed.id'], name=op.f('fk_duplicate_detections_original_opportunity_id_africa_intelligence_feed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_detections'))
    )
    op.create_index(op.f('ix_duplicate_detections_action'), 'duplicate_detections', ['action'], unique=False)
    op.create_index(op.f('ix_duplicate_detections_confidence_score'), 'duplicate_detections', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_duplicate_detections_duplicate_opportunity_id'), 'duplicate_detections', ['duplicate_opportunity_id'], unique=False)
    op.create_index(op.f('ix_duplicate_detections_duplicate_type'), 'duplicate_detections', ['duplicate_type'], unique=False)
    op.create_index(op.f('ix_duplicate_detections_id'), 'duplicate_detections', ['id'], unique=False)
    op.create_index(op.f('ix_duplicate_detections_original_opportunity_id'), 'duplicate_detections', ['original_opportunity_id'], unique=False)
    op.create_table('founder_underrepresented_groups',
    sa.Column('founder_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['founder_id'], ['featured_founders.id'], name=op.f('fk_founder_underrepresented_groups_founder_id_featured_founders')),
    sa.ForeignKeyConstraint(['group_id'], ['underrepresented_groups.id'], name=op.f('fk_founder_underrepresented_groups_group_id_underrepresented_groups'))
    )
    op.create_table('intelligence_item_ai_domains',
    sa.Column('intelligence_item_id', sa.Integer(), nullable=False),
    sa.Column('ai_domain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ai_domain_id'], ['ai_domains.id'], name=op.f('fk_intelligence_item_ai_domains_ai_domain_id_ai_domains'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intelligence_item_id'], ['africa_intelligence_feed.id'], name=op.f('fk_intelligence_item_ai_domains_intelligence_item_id_africa_intelligence_feed'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('intelligence_item_id', 'ai_domain_id', name=op.f('pk_intelligence_item_ai_domains'))
    )
    op.create_table('intelligence_item_geographic_scopes',
    sa.Column('intelligence_item_id', sa.Integer(), nullable=False),
    sa.Column('geographic_scope_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geographic_scope_id'], ['geographic_scopes.id'], name=op.f('fk_intelligence_item_geographic_scopes_geographic_scope_id_geographic_scopes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intelligence_item_id'], ['africa_intelligence_feed.id'], name=op.f('fk_intelligence_item_geographic_scopes_intelligence_item_id_africa_intelligence_feed'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('intelligence_item_id', 'geographic_scope_id', name=op.f('pk_intelligence_item_geographic_scopes'))
    )
    op.create_table('suggested_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('collaboration_id', sa.Integer(), nullable=True),
    sa.Column('intelligence_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaboration_suggestions.id'], name=op.f('fk_suggested_opportunities_collaboration_id_collaboration_suggestions')),
    sa.ForeignKeyConstraint(['intelligence_item_id'], ['africa_intelligence_feed.id'], name=op.f('fk_suggested_opportunities_intelligence_item_id_africa_intelligence_feed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggested_opportunities'))
    )
    op.create_index(op.f('ix_suggested_opportunities_id'), 'suggested_opportunities', ['id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(length=10), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('legitimacy_score', sa.Float(), nullable=True),
    sa.Column('validation_flags', sa.JSON(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('auto_approval_eligible', sa.Boolean(), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=True),
    sa.Column('validator', sa.String(length=50), nullable=True),
    sa.Column('validated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('validated_data', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['africa_intelligence_feed.id'], name=op.f('fk_validation_results_opportunity_id_africa_intelligence_feed')),
    sa.ForeignKeyConstraint(['validated_by_user_id'], ['community_users.id'], name=op.f('fk_validation_results_validated_by_user_id_community_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_results'))
    )
    op.create_index(op.f('ix_validation_results_confidence_level'), 'validation_results', ['confidence_level'], unique=False)
    op.create_index(op.f('ix_validation_results_confidence_score'), 'validation_results', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_validation_results_id'), 'validation_results', ['id'], unique=False)
    op.create_index(op.f('ix_validation_results_opportunity_id'), 'validation_results', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_validation_results_status'), 'validation_results', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_status'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_opportunity_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_confidence_score'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_confidence_level'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_suggested_opportunities_id'), table_name='suggested_opportunities')
    op.drop_table('suggested_opportunities')
    op.drop_table('intelligence_item_geographic_scopes')
    op.drop_table('intelligence_item_ai_domains')
    op.drop_table('founder_underrepresented_groups')
    op.drop_index(op.f('ix_duplicate_detections_original_opportunity_id'), table_name='duplicate_detections')
    op.drop_index(op.f('ix_duplicate_detections_id'), table_name='duplicate_detections')
    op.drop_index(op.f('ix_duplicate_detections_duplicate_type'), table_name='duplicate_detections')
    op.drop_index(op.f('ix_duplicate_detections_duplicate_opportunity_id'), table_name='duplicate_detections')
    op.drop_index(op.f('ix_duplicate_detections_confidence_score'), table_name='duplicate_detections')
    op.drop_index(op.f('ix_duplicate_detections_action'), table_name='duplicate_detections')
    op.drop_table('duplicate_detections')
    op.drop_index(op.f('ix_content_fingerprints_url_hash'), table_name='content_fingerprints')
    op.drop_index(op.f('ix_content_fingerprints_url_domain'), table_name='content_fingerprints')
    op.drop_index(op.f('ix_content_fingerprints_title_hash'), table_name='content_fingerprints')
    op.drop_index(op.f('ix_content_fingerprints_signature_hash'), table_name='content_fingerprints')
    op.drop_index(op.f('ix_content_fingerprints_semantic_hash'), table_name='content_fingerprints')
    op.drop_index(op.f('ix_content_fingerprints_organization_name'), table_name='content_fingerprints')
    op.drop_index(op.f('ix_content_fingerprints_opportunity_id'), table_name='content_fingerprints')
    op.drop_index(op.f('ix_content_fingerprints_id'), table_name='content_fingerprints')
    op.drop_index(op.f('ix_content_fingerprints_funding_amount'), table_name='content_fingerprints')
    op.drop_index(op.f('ix_content_fingerprints_content_hash'), table_name='content_fingerprints')
    op.drop_table('content_fingerprints')
    op.drop_index(op.f('ix_rfps_title'), table_name='rfps')
    op.drop_index(op.f('ix_rfps_id'), table_name='rfps')
    op.drop_table('rfps')
    op.drop_table('organization_geographic_focus')
    op.drop_table('organization_collaboration')
    op.drop_index(op.f('ix_inclusion_metrics_id'), table_name='inclusion_metrics')
    op.drop_table('inclusion_metrics')
    op.drop_index(op.f('ix_gender_funding_data_id'), table_name='gender_funding_data')
    op.drop_table('gender_funding_data')
    op.drop_index(op.f('ix_featured_founders_id'), table_name='featured_founders')
    op.drop_table('featured_founders')
    op.drop_index(op.f('ix_africa_intelligence_feed_validation_status'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_url_hash'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_title_hash'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_status'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_semantic_hash'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_recipient_organization_id'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_provider_organization_id'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_processing_id'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_organization_id'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_ingestion_module'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_id'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_funding_type_id'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_funding_type'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_deadline_urgency'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_currency'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_content_type'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_community_rating'), table_name='africa_intelligence_feed')
    op.drop_index(op.f('ix_africa_intelligence_feed_application_deadline_type'), table_name='africa_intelligence_feed')
    op.drop_table('africa_intelligence_feed')
    op.drop_index(op.f('ix_underrepresented_groups_id'), table_name='underrepresented_groups')
    op.drop_table('underrepresented_groups')
    op.drop_index(op.f('ix_stage_progression_id'), table_name='stage_progression')
    op.drop_table('stage_progression')
    op.drop_index(op.f('ix_source_quality_source_type'), table_name='source_quality')
    op.drop_index(op.f('ix_source_quality_source_name'), table_name='source_quality')
    op.drop_index(op.f('ix_source_quality_quality_grade'), table_name='source_quality')
    op.drop_index(op.f('ix_source_quality_id'), table_name='source_quality')
    op.drop_table('source_quality')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_priority'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_module_type'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_type'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_organizations_type'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_source_type'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_role'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_recipient_type'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_provider_type'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_monitoring_status'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_enrichment_status'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_ai_relevance_score'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_africa_relevance_score'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_module_health_status'), table_name='module_health')
    op.drop_index(op.f('ix_module_health_module_type'), table_name='module_health')
    op.drop_index(op.f('ix_module_health_id'), table_name='module_health')
    op.drop_table('module_health')
    op.drop_index(op.f('ix_geographic_scopes_type'), table_name='geographic_scopes')
    op.drop_index(op.f('ix_geographic_scopes_name'), table_name='geographic_scopes')
    op.drop_index(op.f('ix_geographic_scopes_id'), table_name='geographic_scopes')
    op.drop_index(op.f('ix_geographic_scopes_code'), table_name='geographic_scopes')
    op.drop_table('geographic_scopes')
    op.drop_index(op.f('ix_funding_types_name'), table_name='funding_types')
    op.drop_index(op.f('ix_funding_types_id'), table_name='funding_types')
    op.drop_index(op.f('ix_funding_types_category'), table_name='funding_types')
    op.drop_table('funding_types')
    op.drop_index(op.f('ix_funding_stage_metrics_id'), table_name='funding_stage_metrics')
    op.drop_table('funding_stage_metrics')
    op.drop_index(op.f('ix_funding_categories_name'), table_name='funding_categories')
    op.drop_index(op.f('ix_funding_categories_id'), table_name='funding_categories')
    op.drop_table('funding_categories')
    op.drop_index(op.f('ix_data_sources_name'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_community_users_username'), table_name='community_users')
    op.drop_index(op.f('ix_community_users_id'), table_name='community_users')
    op.drop_index(op.f('ix_community_users_email'), table_name='community_users')
    op.drop_table('community_users')
    op.drop_index(op.f('ix_collaboration_suggestions_id'), table_name='collaboration_suggestions')
    op.drop_table('collaboration_suggestions')
    op.drop_index(op.f('ix_ai_domains_name'), table_name='ai_domains')
    op.drop_index(op.f('ix_ai_domains_id'), table_name='ai_domains')
    op.drop_table('ai_domains')
    # ### end Alembic commands ###
